name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - shell: bash
        working-directory: example/rust-lib
        run: rustup toolchain install

      - uses: ./.github/actions/setup-wasm-opt
        with:
          version: '116'

      - shell: bash
        run: pnpm install

      - shell: bash
        run: pnpm biome ci .

      - shell: bash
        run: pnpm tsc --noEmit

      - shell: bash
        run: pnpm run build

      - shell: bash
        working-directory: example
        run: pnpm run build
